# Generated by Django 3.1.3 on 2020-11-15 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.auto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alquiler',
                'verbose_name_plural': 'Alquilers',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='alquiler',
            index=models.Index(fields=['user', 'auto', 'date_start', 'date_end', 'status'], name='autos_alqui_user_id_e11784_idx'),
        ),
    ]
